# Docker-compose boilder plate for yse with drupal development

version: "3.3"

services:
  drupal:
    image: drupal:8.9.19
    container_name: drupal
    volumes:
      # the next line should be a path to your backed up site files and it's location within a drupal install
      - ${FILES_PATH}drupal/${DRUPAL_SITE_FILES}:/var/www/${DRUPAL_SITE_FILES}
      - ${FILES_PATH}apache/sites-available:/etc/apache2/sites-available
      - ${FILES_PATH}apache/sites-enabled:/etc/apache2/sites-enabled
      - ${FILES_PATH}tmp/drupal:/tmp
    ports:
      - 80:80
    restart: always

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      # the below must match those that are stated in your settings.php file
      MYSQL_DATABASE: ${DRUPAL_DB}
      MYSQL_USER: ${DRUPAL_USER}
      MYSQL_PASSWORD: ${DRUPAL_PW}
    ports:
      - 3306:3306

    volumes:
      - ${FILES_PATH}drupal_db/:/var/lib/mysql
      # the next line is used when initiating the database for the first time
      # Place your sql backup (.sh, .sql and .sql.gz files work) in the local directory
      # If a database already exists it will be ignored.
      - ${FILES_PATH}/tmp/drupal_db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: localhost
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
