version: '3'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  drupal:
    image: drupal
    container_name: drupal
    depends_on: 
      - db
    volumes:
      # the next line should be a path to your backed up site files and it's location within a drupal install
      - ${FILES_PATH}drupal/${DRUPAL_SITE_FILES}:/var/www/${DRUPAL_SITE_FILES}
      - ${FILES_PATH}apache/sites-available:/etc/apache2/sites-available
      - ${FILES_PATH}apache/sites-enabled:/etc/apache2/sites-enabled
    labels:
      - "traefik.http.routers.drupal.entrypoints=websecure"
      - "traefik.http.routers.drupal.rule=Host(`whoami.localhost`, `lamrt.org.uk`, `www.lamrt.org.uk`)"
      - "traefik.http.routers.drupal.tls=true"
    links:
      - db
    restart: always
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 6G

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      # the below must match those that are stated in your settings.php file
      MYSQL_DATABASE: ${DRUPAL_DB}
      MYSQL_USER: ${DRUPAL_USER}
      MYSQL_PASSWORD: ${DRUPAL_PW}
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G

    volumes:
      - ${FILES_PATH}drupal_db/:/var/lib/mysql
